name: Auto Sssign

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  auto-assign:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Assign
        uses: actions/github-script@main
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: `${{ github.actor }}`
            });
