name: Common CI

on:
  pull_request:
    branches:
      - '**'
      - '!main'
      - '!develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup JDK
        uses: actions/setup-java@main
        with:
          distribution: 'microsoft'
          java-version: 17

      - name: Spotless
        run: ./gradlew spotlessCheck
